# Generated by Django 4.2 on 2023-05-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='blood_group',
            field=models.CharField(max_length=5, null='A'),
            preserve_default='A',
        ),
        migrations.AddField(
            model_name='member',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
